### ISSUE TITLE
Publish to RubyGems

### ISSUE THREAD

**Issue by jjasghar** [vmware/vsphere-automation-sdk-ruby#10]
![image](https://media.giphy.com/media/4DB36sA0VpYGs/giphy.gif)

Please Please Please publish this to rubygems, so we can use it in our `gemspec`. If you don't we will need to figure out a way to automatically pull this down, build it locally and inject into our integration. 

![image](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

Thanks!

**Comment by jjasghar** [comment]
https://travis-ci.org/chef/kitchen-vcenter/jobs/274505819 *cough* *cough*

**Comment by donwlewis** [comment]
Would love to see this get integrated as part of base ChefDK!

**Comment by mattstratton** [comment]
👍

**Comment by JustinDevelops** [comment]
Yes Please!

**Comment by swalberg** [comment]
Not wanting to vendor this has also kept me from using it in `knife-vsphere`.

**Comment by smford22** [comment]
+1

**Comment by simfish85** [comment]
Yes we need this ASAP

**Comment by joshbrand** [comment]
👍 !

**Comment by qubitrenegade** [comment]
We'd like to use this for some non-chef work, but as others have stated above, would prefer to use it as part of our `gemspecs`

Thanks!
Q

**Comment by dm4r** [comment]
+1

**Comment by Hendricusk** [comment]
Very nice! Life would be so much easier if it's integrated!

**Comment by trickyearlobe** [comment]
+1 Please publish... it would demonstrate our love of vmWare to customers.

**Comment by bowersna** [comment]
PRETTY PLEASE! ;)

**Comment by gaelik** [comment]
+1

**Comment by jerearista** [comment]
👍 We have numerous uses for this in our in-house automation as well as integrations with other projects once packaging and publishing are complete.  Please publish this to rubygems.

**Comment by jrowme** [comment]
+1

**Comment by donone-apex** [comment]
This would be MOST helpful to have as a Gem!

**Comment by jameswnl** [comment]
please +1

**Comment by tpmullan** [comment]
This would be really helpful!

**Comment by mkennedy85** [comment]
+1 Need this

**Comment by bioxcession** [comment]
<img width="418" alt="screen shot 2017-12-12 at 7 44 23 pm" src="https://user-images.githubusercontent.com/11777705/33917600-e080cba4-df74-11e7-990d-3e83dd44c86e.png">

**Comment by jasonwbarnett** [comment]
+1

**Comment by tas50** [comment]
Another plead to get this published to rubygems. We can't properly test kitchen-vcenter which many large VMware customers are relying on without this. Not pushing this to Rubygems hurts *many* users.

**Comment by strefethen** [comment]
Hi All,
  Thanks for the feedback! We've been working on developing an OpenAPI version of this binding which you can preview [here](https://github.com/vmware/vsphere-automation-sdk-ruby/tree/openapi). Please have a look at let us know your thoughts.

Please note, the new binding will *not* be backwards compatible with the existing binding and we will be providing updated samples and details on the Swagger integration. Additionally, we'll be looking at posting to gems.org following the transition.

Please have a look and offer your feedback!

Regards,
-Steve
Sr Manager R&D
vSphere/VMC SDK's

**Comment by davisvansant** [comment]
> Another plead to get this published to rubygems. We can't properly test kitchen-vcenter which many large VMware customers are relying on without this. Not pushing this to Rubygems hurts _many_ users.

I know everyone has already commented here, but I cant stress enough how amazing it would be to get this going for testing our chef cookbooks on our vmware environment!

**Comment by jameswnl** [comment]
@strefethen the OpenAPI branch says the gem is available from rubygems.org, but it's not there. 

Can you confirm? I may be missing something...

**Comment by jrgarcia** [comment]
@jameswnl It's not currently. I updated the README to reflect the fact that that is the plan once this moves to `master`. For now, you have to build the gems manually, but they will be up on RubyGems once released (which I'm hoping will be very soon).

**Comment by jameswnl** [comment]
thanks @jrgarcia for the clarification.

**Comment by jrgarcia** [comment]
I've merged the `openapi` branch to the `master` branch and pushed the respective gems to RubyGems.org. For installation and use (which has changed), please see the README.
