### ISSUE TITLE
Attribute for Summary of VM is incorrectly cased

### ISSUE THREAD

**Issue by russellseymour** [vmware/vsphere-automation-sdk-ruby#11]
The attribute for the memory of a machine in the Summary class is incorrect. Again this appears to be an incorrectly cased attribute.

This should be `:memory_size_MiB` rather that `:memory_size_mib`. The former is what is returned when a call is made to retrieve the summary of a VM, although it is an object:

```json
        "memory": {
            "size_MiB": 8192,
            "hot_add_enabled": false
        }
```

This attribute can be found on line 3021 in the file `com/vmware/vcenter.rb`. (https://github.com/vmware/vsphere-automation-sdk-ruby/blob/master/client/sdk/com/vmware/vcenter.rb#L3021)

The error is:

```
Exception: NoMethodError: undefined method `memory_size_MiB_=' for #<Com::Vmware::Vcenter::VM::Summary:0x44e55
28>
Did you mean?  memory_size_mib=
               memory_size_mib
```

This may make #5 obsolete because I have not seen this error before and it is different to the error I was getting when I tried to list out machines. I will close #5 if it is no longer an issue.

**Comment by jrgarcia** [comment]
Closed by #12
