### ISSUE TITLE
Error with create_default_vm Sample

### ISSUE THREAD

**Issue by kmruddy** [vmware/vsphere-automation-sdk-ruby#32]
When running the create_default_vm sample, the help output indicates that it needs folder, datastore, and cluster. 

Running the command steps you through the requirement of it actually needing folder, datastore, cluster, VM name, and datacenter.

**Comment by jobingeo** [comment]
The Sample specific options are listed towards the bottom in the '-h' message.  This have the requirement of Folder, Datastore, Cluster, VM Name, Datacenter


XXXXXXX@localhost:~/workspace/vAutomationRubySDK-layer1/vsphere-automation-sdk-ru                                                                                                                                                             by/client/samples/bin$ ./run_sample create_default_vm -h

ruby -I/home/vmware/workspace/vAutomationRubySDK-layer1/vsphere-automation-sdk-r                                                                                                                                                             uby-layer1-cloud/client/sdk/runtime/lib -I/home/vmware/workspace/vAutomationRuby                                                                                                                                                             SDK-layer1/vsphere-automation-sdk-ruby-layer1-cloud/client/sdk -I/home/vmware/wo                                                                                                                                                             rkspace/vAutomationRubySDK-layer1/vsphere-automation-sdk-ruby-layer1-cloud/clien                                                                                                                                                             t/samples/lib lib/sample/vcenter/vm/create/create_default_vm.rb -h
   Demonstrates how to create a VM with system provided defaults
   Author: VMware, Inc.
   Sample Prerequisites:
   The sample needs a datacenter and the following resources:
    - vm folder
    - datastore
    - cluster

Common options:
    -h, --help                       Show this message
        --config [PATH]              Set config file
    -S, --sample-level [LEVEL]       Set sample logging level
    -F, --framework-level [LEVEL]    Set sample framework logging level
    -R, --runtime-level [LEVEL]      Set runtime logging level

General sample options:
    -l, --ls-ip IP                   Lookup service IP address (or hostname)
    -L, --ls-url URL                 Lookup service URL
    -u, --sso-username VALUE         username for SSO login
    -p, --sso-password VALUE         password for SSO login user
    -k, --insecure                   Skip certificate validation
        --ca-file [FILE]             CA file for certificate
    -m, --mgmt-node-index [N]        Management node index (default 0, the first                                                                                                                                                              M node)
    -n, --mgmt-node-id [ID]          Management node ID (get a list by passing a                                                                                                                                                             n invalid value)
    -N, --mgmt-node-name [NAME]      Management node name (get a list by passing                                                                                                                                                              an invalid value)
    -X, --cleanup                    cleanup data after running sample

Specific sample options:
        --datastore-name             Name of the Datastore to locate the VM
    -c, --cluster-name               Name of the Cluster to locate the VM
    -f, --folder-name                Name of the Folder to locate the VM
    -d, --datacenter-name            Name of the Datacenter
    -v, --vm-name NAME               Name of the VM to be created

**Comment by kmruddy** [comment]
The bottom of the help output lists the available options. The requirements are higher in the help statement: 
> Sample Prerequisites:
>The sample needs a datacenter and the following resources:
>- vm folder
>- datastore
>- cluster

Now that I re-read it again, I see that 'datacenter' is listed, but not in the bullet points. That option should either be in the bullet points or removed from the requirements. The REST call itself doesn't have a requirement for a datacenter object, so I'd like to see that requirement removed. 

That still leaves the name, which is another option that isn't required on the backend REST call. (or, it's needed to be added to the requirements list)

**Comment by jobingeo** [comment]
Agreed. This help statement should be modified in  this section.
