### ISSUE TITLE
Why do you need to use SOAP to perform the authentication?

### ISSUE THREAD

**Issue by russellseymour** [vmware/vsphere-automation-sdk-ruby#4]
Does SOAP provide something that just using the REST API does not?

For example I have used Ruby `net/http` and Postman to make a POST request against `/rest/com/vmware/cis/session` using Basic auth and I get session id.

It occurs to me that maybe the SOAP response provides the correct machine to authenticate against whereas you have to know the endpoint to authenticate using the REST API - however if this is not the case then having to use SOAP for _just_ the login seems very overkill.

**Comment by jrgarcia** [comment]
We talked about this privately, so I'm just adding this for anyone reading.

The SOAP call is used to use the lookup service to find the correct host to authenticate against. This is only necessary if you have an external PSC (platform services controller). If it is embedded this isn't necessary. I will look at updating this in the future. Maybe allowing you to flag whether your PSC is embedded or external? At any rate, I do think that this adds a little confusion to people using this, especially if they have only ever worked with an embedded PSC.

Thanks for reporting!

**Comment by jrgarcia** [comment]
Closing as this is no longer relevant due to the changes made to the SDK
