### ISSUE TITLE
How do I get EVC Cluster state

### ISSUE THREAD

**Issue by vbaranikumar** [vmware/vsphere-automation-sdk-ruby#43]
Team,

Is there any example ruby code to get EVC cluster state?

Thanks,
Barani Kumar

**Comment by jrgarcia** [comment]
Hey @vbaranikumar, unfortunately, there isn't a REST API call available for that so there is nothing in this Ruby SDK that would get that information. That should be available in [RbVmomi](https://github.com/vmware/rbvmomi) though.
