### ISSUE TITLE
Unable to return a list of virtual machines

### ISSUE THREAD

**Issue by russellseymour** [vmware/vsphere-automation-sdk-ruby#5]
I am trying to return a list of VMs from the vCenter cluster that I am authenticated against using the following code:

```ruby
vm = Com::Vmware::Vcenter::VM.new(vapi_config)
puts vm.list()
```

However I get the following error:

```
E, [2017-07-03T15:43:03.062179 #11156] ERROR -- vAPI: failed to dynamically resolve binding type: Com::Vmware::Vcenter::Vm::Power::State
E, [2017-07-03T15:43:03.068256 #11156] ERROR -- vAPI: uninitialized constant Com::Vmware::Vcenter::Vm
Did you mean?  Com::Vmware
               Com::Vmware::Vcenter::VM (NameError)
```

**Comment by russellseymour** [comment]
I am closing this as I am no longer getting this exact error. However I have created #11 because the memory is not reported back properly.

**Comment by jrgarcia** [comment]
My guess would be that `com/vmware/vcenter` was `require`d, but `com/vmware/vcenter/vm` was not. I'm looking at the `guest_OS` and `memory_size_MiB` issues right now.
