### ISSUE TITLE
API error with array parameters

### ISSUE THREAD

**Issue by smoeding** [vmware/vsphere-automation-sdk-ruby#53]
## Describe the bug

I want to use the `list` methods to filter on multiple conditions. As soon as I use array parameters, I get an API error.

## How to reproduce

Take the sample program `samples/vsphere/vcenter/vm/list-vms`. This gives a list of all VMs. Now update line 44 from

```ruby
vms = vm_api.list
```
to 
```ruby
vms = vm_api.list(filter_vms: 'vm-8768')
```

This gives the list with only the one specified VM. Good.
Now update the same line to

```ruby
vms = vm_api.list(filter_vms: ['vm-8768'])
```
Now I get the following error:

```
#<VSphereAutomation::VCenter::VapiStdErrorsUnableToAllocateResourceError:0x0055a2eee06988
 @type="com.vmware.vapi.std.errors.unexpected_input",
 @value=
  #<VSphereAutomation::VCenter::VapiStdErrorsUnableToAllocateResource:0x0055a2eee06730
   @messages=
    [#<VSphereAutomation::VCenter::VapiStdLocalizableMessage:0x0055a2eee062d0
      @args=["[vms[0]]", "com.vmware.vcenter.VM.filter_spec"],
      @default_message=
       "Found unexpected fields [vms[0]] in structure 'com.vmware.vcenter.VM.filter_spec'.",
      @id="vapi.data.structure.field.unexpected">]>>
```

## Expected behavior

From the API documentation I would expect that the parameter is `Array<String>`:
https://vmware.github.io/vsphere-automation-sdk-ruby/VSphereAutomation/VCenter/VMApi.html#list-instance_method

So I would expect the call to succeed.

## Versions

**Dev Environment:**

* Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
* vSphere Automation SDK: 0.2.0
* OS: Debian GNU/Linux 9.9 (stretch)

## Additional notes

I enabled debugging and the following request fails:
```
GET /rest/vcenter/vm?filter.vms%5B0%5D=vm-8768 HTTP/1.1
```

From the API doc https://vmware.github.io/vsphere-automation-sdk-ruby/VSphereAutomation/VCenter/VMApi.html#list-instance_method I would expect to see this:

```
GET /rest/vcenter/vm?filter.vms.1=vm-8768 HTTP/1.1
```

**Comment by jrgarcia** [comment]
This should _absolutely_ work. I'll look into why, but as a workaround in the meantime, you can do `:'filter.vms' => ['vm-8768']`. This seems to work. I suspect that the issue is related to how it is building the query params.

**Comment by jrgarcia** [comment]
Actually, I take that back. It doesn't error out, but it isn't filtering either. 🤦‍♂ I think I found the issue. I'll release a fix for it soon.

**Comment by jrgarcia** [comment]
This should be fixed in [the latest release](https://rubygems.org/gems/vsphere-automation-sdk/versions/0.2.2). Thanks for opening this issue!

**Comment by smoeding** [comment]
I tested this with filtering VMs on power state and that works as expected.
Thanks!
