### ISSUE TITLE
Cannot clone a machine

### ISSUE THREAD

**Issue by russellseymour** [vmware/vsphere-automation-sdk-ruby#6]
Having authenticated against the vCenter cluster I want to clone a virtual machine. This is the code that I am using to do this:

```ruby
        def create_server(options={})
          # Create a new CloneSpec object to work with
          clonespec = Com::Vmware::Vcenter::VM::CloneSpec.new()
          clonespec.source = options[:source]
          clonespec.name = options[:name]

          # Create the new machine
          vmobj = Com::Vmware::Vcenter::VM.new(vapi_config)
          vm = vmobj.clone(clonespec)
        end
```

The `vapi_config` object has a session id set and the `vmobj` is created successfully, however when I try to clone the machine, on the next line, I get the following error:

```
E, [2017-07-11T11:11:24.084197 #22056] ERROR -- vAPI: VapiError (Com::Vmware::Vapi::Std::Errors::Unauthenticated)

ERROR: Com::Vmware::Vapi::Std::Errors::Unauthenticated: VapiError
```

It seems that the session id has been lost in the `vmobj` so when I try to perform operations on it I get the Unauthenticated error.

**Comment by jrgarcia** [comment]
The Automation SDK and the REST API does not support cloning at this time.
