### ISSUE TITLE
API provides not enough information

### ISSUE THREAD

**Issue by smoeding** [vmware/vsphere-automation-sdk-ruby#61]
## Describe the bug

I'm not sure if I am missing something but I can't find a way to get enough information from the API results to create a new VM in a given network.

## How to reproduce

 I have a vSphere installation with multiple clusters in a datacenter. The clusters have common networks created with the same name.

If I use the list method for my VSphereAutomation::VCenter::NetworkApi object, I get an array of VSphereAutomation::VCenter::VcenterNetworkSummary objects which don't have any attribute that indicates the cluster:

```
[#<VSphereAutomation::VCenter::VcenterNetworkSummary:0x0055aec0784690
  @name="3040_IZJ_KickDepNet",
  @network="dvportgroup-575",
  @type="DISTRIBUTED_PORTGROUP">
 #<VSphereAutomation::VCenter::VcenterNetworkSummary:0x00562b5f086048
  @name="3040_IZJ_KickDepNet",
  @network="dvportgroup-576",
  @type="DISTRIBUTED_PORTGROUP">]
```

How can I find out, which network is in which cluster? I don't see any filter that allows me to list only networks in a given cluster.

## Versions

**Dev Environment:**

* Ruby: 2.3.3p222
* vSphere Automation SDK: 0.4.4
* OS: Debian-9 Stretch

**Comment by jrgarcia** [comment]
Unfortunately, that is a limitation of the REST API currently so I have no way of exposing that information through this SDK. I'm going to close for now, but I will pass this feedback along for the REST API. Thanks for reporting!

**Comment by smoeding** [comment]
In my opinion there is more that the API should expose.
Could you point me to a better place to address those?

Thanks!
