### ISSUE TITLE
gems are shipped in the gems

### ISSUE THREAD

**Issue by tas50** [vmware/vsphere-automation-sdk-ruby#63]
## Describe the bug

The gemspec is just finding all the files in the repo dir and shipping those in the gem artifact. It looks like the pipeline or workstation where these are running has all the previous versioned gems in the pkg dir. These are being shipped in each release. In all the gems this ends up being about 9 megs on disk that isn't needed.

## How to reproduce

Open up the installed gem and check the pkg dir

## Expected behavior

Only the minimal files necessary are shipped

**Comment by jrgarcia** [comment]
Weird. This shouldn't be happening at all. I'll get this fixed ASAP.

**Comment by tas50** [comment]
I can cut a PR that slims it down to just the minimal files

**Comment by jrgarcia** [comment]
I definitely welcome PRs! :smile:

**Comment by tas50** [comment]
How would you feel about just shipping the lib dir in the artifact? That seems to be where folks are moving in rubygems so that the install artifact is *just* the necessary runtime files and nothing more.

**Comment by jrgarcia** [comment]
That should be fine. The spec says that only files that can be required should be included and other than the `lib` directory, there is only `spec` and `docs` (neither of which should be included).
