### ISSUE TITLE
Individual gem artifacts should ship with an artifact

### ISSUE THREAD

**Issue by tas50** [vmware/vsphere-automation-sdk-ruby#65]
## Describe the bug

Even though the gemspec defined the license the gem should also ship the MIT license with the copyright comment in that file. These files are often read by license scanner tools to determine compliance. We have an internal tool at Chef that scans our products and it fails on these gems since they don't contain the actual license file to be validated.

## How to reproduce

Check the installed individual gems for a license file

## Expected behavior

The gem ships an MIT license file

## Versions
 
0.4.5

**Comment by jrgarcia** [comment]
I've added the `LICENSE` file to all gems and pushed out a new version (`v0.4.6`) which this and your gemspec changes. Thanks! 🎉
