### ISSUE TITLE
Cannot get the id of the specified datastore

### ISSUE THREAD

**Issue by russellseymour** [vmware/vsphere-automation-sdk-ruby#7]
During creation of new machines it is necessary to get the actual id of the datastore and not the display that is seen.

To do this I retrieve the information using a FilterSpec on the specified class, however if I do the following on the datastore:

```ruby
        def get_datastore(name)
          filter = Com::Vmware::Vcenter::Datastore::FilterSpec.new({names: Set.new([name])})
          datastore_obj = Com::Vmware::Vcenter::Datastore.new(vapi_config)
          datastore = datastore_obj.list(filter)
          datastore[0].datastore
        end
```

I get the following error:

```
lib/vapi/protocol/client/msg/json_rpc.rb:96:in `create_data_value': unexpected type found in a JSON RPC response (RuntimeError)
```

I believe this is a parsing issue with the response because when I perform the same action using Postman I get a valid object back from vCenter:

Target URI: `/rest/vcenter/datastore?filter.names=datastore1`
```json
{
    "value": [
        {
            "datastore": "datastore-29",
            "name": "datastore1",
            "type": "VMFS",
            "free_space": 1282856189952,
            "capacity": 1992059518976
        }
    ]
}
```

This appears to be an issue with the `datastore` class because I use the same FilterSpec idea on `host` and `folders` and it works without issue.

**Comment by jrgarcia** [comment]
Closing as this is no longer relevant due to the changes made to the SDK. Please feel free to reopen if this continues to be an issue.
