### ISSUE TITLE
Unable to attach tags to vCenter objects

### ISSUE THREAD

**Issue by thomastnguyen1995** [vmware/vsphere-automation-sdk-ruby#70]
## Describe the bug
This is not necessarily a bug - I just could not get tags attached to vCenter objects using the CIS and vCenter APIs. I was hoping we could close any knowledge gaps here or find anything wrong with how I am attempting to accomplish this.

## How to reproduce

```ruby
tag_association_api = VSphereAutomation::CIS::TaggingTagAssociationApi.new(@rest)
request_body = VSphereAutomation::CIS::CisTaggingTagAssociationAttach.new(object_id: <object_id>)
tag_association_api.attach(@id, request_body).value
```
The value that is returned is nil for each example that I tried.

Examples passed in for object_id (most of these were retrieved using attributes from VSphereAutomation::VCenter::ClusterApi):
	⁃	'VSphereAutomation::CIS::VapiStdDynamicID:0x00007f87c3d662d8' (It should be this one from my understanding. Am I just formatting it incorrectly?)
	⁃	'domain-c26'
	⁃	'resgroup-27'
	⁃	'VSphereAutomation::VCenter::VcenterClusterInfo:0x00007fc8fba7f0a0'
	⁃	<String name of the cluster>

## Expected behavior

vCenter tag can become attached to a given vCenter object.

## Versions

**Dev Environment:**

* Ruby: 2.6.3
* vSphere Automation SDK: 0.4.6
* OS: macOS 10.15.4

## Additional notes

_Add any other notes about the problem here._

**Comment by jrgarcia** [comment]
I'm having some trouble with this as well. Let me look into this a see what's going on. Thanks for reporting!

**Comment by jrgarcia** [comment]
Ok, I've found the issue. If you look at the documentation [here](https://vmware.github.io/vsphere-automation-sdk-rest/vsphere/operations/com/vmware/cis/tagging/tag_association.attach-operation.html), you'll see that the request body's structure is not what you were expecting it to be (to be honest, I wasn't either). Your code should be,
```ruby
tag_association_api = VSphereAutomation::CIS::TaggingTagAssociationApi.new(@rest)
object_id = VSphereAutomation::CIS::VapiStdDynamicID.new(id: <moid of cluster>, type: 'CLUSTER')
request_body = VSphereAutomation::CIS::CisTaggingTagAssociationAttach.new(object_id: object_id)
tag_association_api.attach(@id, request_body).value
```

Notice the second line, in the code above. If you would like to attach this to another type of object (Folder, Datacenter, Datastore, etc.), you would still set the `id` to the moid of that object. The `type` is the resource type as a string, all uppercase, replacing spaces with underscores (e.g. Resource Pool would be `'RESOURCE_POOL'`). Unfortunately, these `type`s are not defined as constants anywhere. Let me know if that helps!

**Comment by thomastnguyen1995** [comment]
Thank you for investigating J.R.!

For the moid of the cluster, should I be able to retrieve that value from the `VSphereAutomation::VCenter::ClusterApi` class? Reading through the documentation, I found it needs to be structured like `"obj-103"`. I have a value similar to that from the cluster API that looks like `"domain-c26"` but that is not attaching correctly. Do you see anything that could be wrong here?

**Comment by jrgarcia** [comment]
So for that instance, your code would need to be

```ruby
tag_association_api = VSphereAutomation::CIS::TaggingTagAssociationApi.new(@rest)
object_id = VSphereAutomation::CIS::VapiStdDynamicID.new(id:'domain-c26', type: 'CLUSTER')
request_body = VSphereAutomation::CIS::CisTaggingTagAssociationAttach.new(object_id: object_id)
tag_association_api.attach(@id, request_body).value
```

Is that what you have? Notably, the line `object_id = VSphereAutomation::CIS::VapiStdDynamicID.new(id:'domain-c26', type: 'CLUSTER')`

**Comment by thomastnguyen1995** [comment]
Yes, that is exactly what I have!
The ID I have for the tag is formatted as such: `urn:vmomi:InventoryServiceTag:737ca4dc-bf14-4129-aa36-6c8a6f34cfd5:GLOBAL`. Maybe that's incorrect?

**Comment by jrgarcia** [comment]
That’s correct. I’m not sure. This is working in multiple test environments for me. What version of vCenter is this?

**Comment by thomastnguyen1995** [comment]
`6.7.0.44000`

**Comment by thomastnguyen1995** [comment]
Following up just in case anyone else has the same issue - I was able to get tags attached but the `type` that I had to pass into this line for clusters was `ClusterComputeResource`.

`VSphereAutomation::CIS::VapiStdDynamicID.new(id:'domain-c26', type: 'ClusterComputeResource')`

**Comment by jrgarcia** [comment]
Thanks for adding that @thomastnguyen1995! I'm not sure why it was working for me with just `'CLUSTER'`. I'll have to look into that. Glad it's working for you now though!
