### ISSUE TITLE
0.5.0 not actually on rubygems.org

### ISSUE THREAD

**Issue by jstange** [vmware/vsphere-automation-sdk-ruby#71]
Per the README, the following should work:

```
gem 'vsphere-automation-sdk', '~> 0.5.0'
```

However, only 0.4.6 appears to be published:

https://rubygems.org/gems/vsphere-automation-sdk

Did someone forget a `gem push`?

**Comment by jrgarcia** [comment]
No, the push wasn't forgotten. It's do to an issue with the filename length of Gems. The generator has a few places that it generated filenames that have gone over the maximum length. It works just fine if you require it, but you can't package it as a Gem. I haven't had a chance to work around this yet, but I'll update the README to avoid the confusion.

Thanks for noting this!
